version: 2.1

jobs:
  check-tranlate-commit:
    machine:
      image: ubuntu-2004:202111-02
    resource_class: medium
    steps:
      - checkout
      - run:
          name: check-tranlate-commit-by-ssh
          command: |
            git config --global user.email "sam.li@sparticle.com"
            git config --global user.name "sam li"
            strmid=$(git rev-parse HEAD)
            if git log 9b8bebd422fd253406996f06a716f22e11e66290 --stat -1 | grep -q "files changed" ;  then  exit 2
              fi
            strmmsg=$(git log --pretty=format:"%s" $strmid -1)
            strPOEditor="Update.*\(POEditor.com\)"
            if [[ $strmmsg =~ $strPOEditor ]]
            then
              git fetch origin
              strwk=$(for branch in `git branch -r | grep -v HEAD | grep '[0-9]*.wk[0-9]*$'`;do echo -e `git show --format="%ci %cr" $branch | head -n 1` \\t$branch; done | sort -r | head -1)
              strwk=${strwk#*/}
              git checkout $strwk
              git cherry-pick $strmid
              git push 
              git checkout main


            else
              echo "非POEditor代码提交"
            fi
  demo_build:
    machine:
      image: ubuntu-2004:202111-02
    resource_class: medium
    steps:
      - checkout
      - run:
          name: demo_build 
          # 如果 job check-tranlate-commit执行完成，但是检测到空的翻译commit，不进行cheery pick 以及后续ci的build
          command: |
            echo "should not in when translate commit is empty!"

workflows:
  version: 2.1
  build-and-deploy:
    jobs:
      - check-tranlate-commit:
          filters:
            branches:
              only: main # only deploy on the main branch
      - demo_build:
          requires:
            - check-tranlate-commit
          filters:
            branches:
              only: main # only deploy on the main branch
      