version: 2.1

jobs:
  check-tranlate-commit:
    machine:
       image: ubuntu-2004:202111-02
    resource_class: medium
    steps:
      - run:
          name: check-tranlate-commit-by-ssh
          command: |
            echo "todo"

workflows:
  version: 2.1
  build-and-deploy:
    jobs:
      - check-tranlate-commit:
          requires:
            - check-tranlate-commit # only deploy once build job has completed
          filters:
            branches:
              only: main # only deploy on the main branch
       